### ISSUE TITLE
Use const and let instead of var

### ISSUE THREAD

**Issue by marsonya** [google/CodeCity#436]
Section 5.1.1 of the [google style guide](https://google.github.io/styleguide/jsguide.html) states:-
"Declare all local variables with either `const` or `let`. Use `const` by default, unless a variable needs to be reassigned. The `var` keyword must not be used."

The current code has a lot of var use.

**Comment by marsonya** [comment]
@cpcallen, I would like to help with this one.

**Comment by NeilFraser** [comment]
While developing Code City, we are hopping back and forth between code for the server and code for the database and code for the browser.  All three are JavaScript.  But the database is currently limited to (mostly) ES5.  Thus to avoid confusion we try to keep all our code (mostly) ES5.  Our general principle is that as we unlock new features to our interpreter, then we allow ourselves to use that feature in the server or the browser.

Thus, as long as `const` and `let` are unsupported in the database, we'd like to avoid using them elsewhere.  Otherwise we'll start making mistakes when writing database code.

**Comment by marsonya** [comment]
Understood. Thanks for the Explanation.
Am closing this issue.
